infile: /media/bigvol/benoit/MitoNucl/DILS/biguttulus_brunneus_DILS_3rd_small.fst  
region: coding  
nspecies: 2  
nameA: biguttulus  
nameB: burnus
nameOutgroup: NA  
lightMode: FALSE
useSFS: 0
config_yaml: /media/bigvol/benoit/MitoNucl/DILS/config_biguttulus_brunneus_3rd_small.yaml  
timeStamp: biguttulus_brunneus_3rd_small
population_growth: variable  
modeBarrier: bimodal  
max_N_tolerated: 0.4 
Lmin: 100
nMin: 20 
mu: 0.0000000015  
rho_over_theta: 0.5  
N_min: 10  
N_max: 200000000  
Tsplit_min: 10  
Tsplit_max: 10000000  
M_min: 0 
M_max: 200
